version: '3'
services:
  frontend:
    build:
      context: ./front  
      dockerfile: Dockerfile 
    ports:
      - "8080:80"  

  backend:
    build:
      context: ./back
      dockerfile: Dockerfile  
    ports:
      - "5000:5000"  
    environment:
      - FLASK_ENV=development
