version: '3'
services:
  frontend:
    build:
      context: ./front  
      dockerfile: Dockerfile 
    ports:
      - "8080:80"  
    depends_on:
      - backend

  backend:
    build:
      context: ./back
      dockerfile: Dockerfile  
    ports:
      - "5050:5050"  
    environment:
      - FLASK_ENV=development
